gaMainArray100[1]="En 1971 pizza hut se convirtio en la cadena <b>#1</b> de pizzas tanto en ventas como en número de restaurantes a nivel mundial.";	
gaMainArray70[2]="<a class = SmallMenuLink href=https://www.yumnet.com/eprise/main/yumnet/login?EprSecureRedir=1 target=_blank>Yum! Buzz International</a>";	
gaMainArray70[3]="<a class = SmallMenuLink href=http://webmail.yum.com/ target=_blank>WebMail</a>";	
gaMainArray70[4]="<a class = SmallMenuLink href=http://www.seccionamarilla.com.mx/ target=_blank>Sección Amarilla</a>";	
gaMainArray70[5]="<a class = SmallMenuLink href=http://www.skytel.com.mx/ target=_blank>SkyTel</a>";	
gaMainArray70[6]="<a class = SmallMenuLink href=http://www.bancomer.com.mx/ target=_blank>Bancomer</a>";	
gaMainArray70[7]="<a class = SmallMenuLink href=http://www.cnn.com.mx/ target=_blank>CNN Español</a>";	
gaMainArray20[1]="<a class = SmallMenuLink href=/Finance/Bulletin/Entry/BulletinYum.html target=ifrMainContainer target=_blank>Boletín de finanzas</a>";	
gaMainArray70[1]="<a class = SmallMenuLink href=http://moneycentral.msn.com/investor/research/msnbc/newsnap.asp?SYMBOL=yum target=_blank>Acciones Yum</a>";	
gaMainArray10[1]="Si quieres que te hagan algo, encárgaselo a una persona ocupada<br><b>Stephen Covey </b>";	
gaMainArray20[3]="<a class = SmallMenuLink href=/Marketing/PH/Files/promodvd.MPG target=_blank>Anuncio PH - DVD&nbsp;&nbsp;&nbsp;<img src = '/Images/Wellcome/new.gif' border = 0></a>";	
gaMainArray20[2]="<a class = SmallMenuLink href=/HR/Directory/Files/DirectoryYum.html target=_blank>Directorio telefónico&nbsp;&nbsp;&nbsp;<img src = '/Images/Wellcome/new.gif' border = 0></a>";	
gaMainArray20[5]="<a class = SmallMenuLink href=/HR/Events/HutClub/Entry/EventsYum.html target=ifrMainContainer target=_blank>Eventos Yum</a>";	
gaMainArray20[4]="<a class = SmallMenuLink href=/Finance/PurchaseOrder/Files/PFSProductsYum.html target=_blank>Productos de PFS&nbsp;&nbsp;&nbsp;<img src = '/Images/Wellcome/new.gif' border = 0></a>";	
gaMainArray30[15]="-FABIAN AYALA<b>&nbsp;-TECNICO EN MANTENIMIENTO</b><br>";	
gaMainArray30[16]="-OSBALDO DANIEL ESCALON<b>&nbsp;-ADMINISTRADOR DE CONTR. DE ARREND.</b><br>";	
gaMainArray30[17]="-JOSE ALEJANDRO MARTINEZ<b>&nbsp;-GERENTE LIDER DE UNIDAD KFC</b><br>";	
gaMainArray40[1]=" <font class = descriptionTabla><b>Aperturas 2004</b></font><br><br>";	
gaMainArray40[8]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;453 Leyva Solano (Jul 30 2004)<br>";	
gaMainArray40[7]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;451 Pachuca (Jun  1 2004)<br>";	
gaMainArray40[2]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;447 Cuautla (Mar  7 2004)<br>";	
gaMainArray40[3]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;442 Tlalnepantla (Mar 20 2004)<br>";	
gaMainArray40[4]=" <img src = '/Images/Wellcome/kfc_mini_icon.gif' border = 0>&nbsp;824 Plaza Cachanilla (Mar 24 2004)<br>";	
gaMainArray40[5]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;448 Texcoco (Mar 29 2004)<br>";	
gaMainArray40[6]=" <img src = '/Images/Wellcome/kfc_mini_icon.gif' border = 0>&nbsp;822 KFC HERMOSILLO SUR (May  6 2004)<br>";	
gaMainArray40[10]=" <br><font class = descriptionTabla><b>Proximas aperturas</b></font><br><br>";	
gaMainArray40[11]=" <img src = '/Images/Wellcome/kfc_mini_icon.gif' border = 0>&nbsp;Palomar GDL<br>";	
gaMainArray40[12]=" <img src = '/Images/Wellcome/kfc_mini_icon.gif' border = 0>&nbsp;Monclova<br>";	
gaMainArray40[13]=" <img src = '/Images/Wellcome/kfc_mini_icon.gif' border = 0>&nbsp;Ejercito Mexicano Mazatlan<br>";	
gaMainArray40[14]=" <img src = '/Images/Wellcome/kfc_mini_icon.gif' border = 0>&nbsp;Tlaxcala<br>";	
gaMainArray40[15]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;Oaxaca<br>";	
gaMainArray40[16]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;Pablo Valdez GDL<br>";	
gaMainArray40[17]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;Independencia Torreon<br>";	
gaMainArray40[18]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;Mirador Chih<br>";	
gaMainArray40[19]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;San Pedro de los pinos<br>";	
gaMainArray40[20]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;El Coyol, Ver.<br>";	
gaMainArray40[21]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;Leyva Solano, Culiacan<br>";	
gaMainArray40[9]=" <img src = '/Images/Wellcome/ph_mini_icon.gif' border = 0>&nbsp;454 El Coyol (Sep  7 2004)<br>";	
gaMainArray50[39]="-JOSE ROJAS<b>&nbsp;(November 1, 10 Años)</b><br>";	
gaMainArray50[40]="-OTHON BERTIN CARRILLO<b>&nbsp;(November 1, 2 Años)</b><br>";	
gaMainArray50[41]="-HECTOR AURELIO PARADA<b>&nbsp;(November 3, 1 Año)</b><br>";	
gaMainArray50[42]="-LUZ MARIA SUBERZA<b>&nbsp;(November 6, 3 Años)</b><br>";	
gaMainArray50[43]="-GUADALUPE LEYSA RANGEL<b>&nbsp;(November 9, 6 Años)</b><br>";	
gaMainArray50[44]="-RAUL EZQUERRO<b>&nbsp;(November 9, 12 Años)</b><br>";	
gaMainArray50[45]="-MARTHA GARCIA<b>&nbsp;(November 9, 12 Años)</b><br>";	
gaMainArray50[46]="-RENE LOPEZ<b>&nbsp;(November 21, 10 Años)</b><br>";	
gaMainArray50[47]="-ANTONIO EDUARDO AGUILAR<b>&nbsp;(November 21, 3 Años)</b><br>";	
gaMainArray50[48]="-MARCELO SEGURA<b>&nbsp;(November 22, 10 Años)</b><br>";	
gaMainArray50[49]="-PABLO MENDOZA<b>&nbsp;(November 22, 11 Años)</b><br>";	
gaMainArray50[50]="-LILIANA MONTSERRAT GARCIA<b>&nbsp;(November 25, 8 Años)</b><br>";	
gaMainArray50[51]="-CESAR ARMANDO LIZARRAGA<b>&nbsp;(November 26, 2 Años)</b><br>";	
gaMainArray50[52]="-SERGIO ALBERTO RAMIREZ<b>&nbsp;(November 28, 3 Años)</b><br>";	
gaMainArray60[53]="-ROSA MARIA URBINA<b>&nbsp; (November 3)</b><br>";	
gaMainArray60[54]="-LILIANA ORTIZ<b>&nbsp; (November 6)</b><br>";	
gaMainArray60[55]="-CARINA PINONES<b>&nbsp; (November 7)</b><br>";	
gaMainArray60[56]="-LEOPOLDO ROSALES<b>&nbsp; (November 10)</b><br>";	
gaMainArray60[57]="-FRANCISCO JAVIER BARBERENA<b>&nbsp; (November 11)</b><br>";	
gaMainArray60[58]="-ILEANA ROMERO<b>&nbsp; (November 11)</b><br>";	
gaMainArray60[59]="-MONICA ESTELA ALVAREZ<b>&nbsp; (November 11)</b><br>";	
gaMainArray60[60]="-VANESSA HIDALGO<b>&nbsp; (November 16)</b><br>";	
gaMainArray60[61]="-JULIAN MONTERROSA<b>&nbsp; (November 16)</b><br>";	
gaMainArray60[62]="-LAURA ALICIA REGUEIRA<b>&nbsp; (November 17)</b><br>";	
gaMainArray60[63]="-HECTOR AVINA<b>&nbsp; (November 19)</b><br>";	
gaMainArray60[64]="-GERARDO RUIZ<b>&nbsp; (November 19)</b><br>";	
gaMainArray60[65]="-ROSA MARTHA MASTACHE<b>&nbsp; (November 22)</b><br>";	
gaMainArray60[66]="-SANTIAGO SAPINA<b>&nbsp; (November 22)</b><br>";	
gaMainArray60[67]="-ERIKA ADRIANA GOMEZ<b>&nbsp; (November 24)</b><br>";	
gaMainArray60[68]="-ALEJANDRO GARCIA<b>&nbsp; (November 25)</b><br>";	
gaMainArray60[69]="-DORA ALICIA RAMOS<b>&nbsp; (November 26)</b><br>";	
gaMainArray60[70]="-RENE LOPEZ<b>&nbsp; (November 27)</b><br>";	
gaMainArray60[71]="-CONCEPCION HURTADO<b>&nbsp; (November 28)</b><br>";	
gaMainArray60[72]="-MIGUEL ANGEL ZAVALETA<b>&nbsp; (November 30)</b><br>";	
